version: 2.1

orbs:
  docker: circleci/docker@2.1.1 # L'orb pour gérer Docker

executors:
  vm-executor:
    machine: true
    working_directory: ~/app

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  build-docker:
    executor: vm-executor
    steps:
      - checkout
      - docker/build:
          path: .
          image: monapp:latest # L'argument image est ici au lieu de tag

      - docker/run:
          name: Test Docker image
          image: monapp:latest
          command: |
            sleep 10  # Attendre un peu plus longtemps pour s'assurer que l'application démarre
            curl --fail http://127.0.0.1:8080/ || exit 1

      - docker/push:
          username: "$DOCKER_USERNAME"
          password: "$DOCKER_PASSWORD"
          image: "$DOCKER_USERNAME/monapp:latest"

workflows:
  version: 2
  build-workflow:
    jobs:
      - say-hello
      - build-docker
