version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:current

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  build-docker:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t monapp:latest .

      - run:
          name: Test Docker image
          command: |
            docker run --rm -d -p 8080:8080 --name test-container monapp:latest
            sleep 30  # Attendre que le conteneur démarre
            curl -f http://0.0.0.0:8080 || (echo "L'application ne répond pas" && exit 1)
            docker stop test-container

workflows:
  version: 2
  build-workflow:
    jobs:
      - say-hello
      - build-docker
