version: 2.1

orbs:
  docker: circleci/docker@2.1.1 # L'orb pour gérer Docker

executors:
  vm-executor:
    machine: true
    working_directory: ~/app

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  build-docker:
    executor: vm-executor
    steps:
      - checkout

      - docker/build:
          image: monapp:latest
          path: .

      - docker/push:
          username: "$DOCKER_USERNAME"
          password: "$DOCKER_PASSWORD"
          image: "$DOCKER_USERNAME/monapp:latest"

workflows:
  version: 2
  build-workflow:
    jobs:
      - say-hello
      - build-docker
