name: CI/CD Pipeline

on:
  push:
    branches:
      - circleci-project-setup

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/monapp:latest

      - name: Run container for testing
        run: |
          docker run -d -p 8080:8080 --name test-container ${{ secrets.DOCKER_USERNAME }}/monapp:latest
          sleep 10
          curl --fail http://127.0.0.1:8080/ || exit 1
          docker stop test-container
